max_width = 105
indent_style = "Block"
fn_single_line = true
format_strings = true
merge_imports = false
match_block_trailing_comma = true
merge_derives = true
normalize_comments = true
reorder_impl_items = true
fn_args_density = "Compressed"