language: rust

rust:
- nightly

before_script:
- rustup component add rustfmt-preview
- rustup component add clippy-preview
- cargo install cargo-audit

script:
- cargo fmt --all -- --check
- cargo build
- cargo audit
- cargo clippy
- cargo test


after_success:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"

after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"